defaults:
  - problem: newsvendor
  - method: robust
  - problem/newsvendor/distribution: norm
  - problem/newsvendor/dim: dim_1
  - _self_

seed: 42
risk_level: 0.05
solver: gurobi
time_limit: 36000 # 10 hours in seconds

samples:
  xi: 100000
  xi_validation: 50000
  xi_test: 100000
  x: 10000000
  cartesian_product: false

mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "SO_${problem.name}"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${problem.name}/${method.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
