_target_: stochopt.problem.newsvendor.NewsvendorProblem
name: newsvendor2_exp
n_products: 2
costs: [1.0, 1.0]
prices: [2.0, 2.0]
demand_dist: "exponential"
demand_params:
  mean: [5.0, 10.0]
  std: [1.0, 2.0]
x_density: "uniform"
correlated: false
